### ISSUE TITLE
graphic issue on chrome

### ISSUE THREAD

**Issue by marcofaion** [lovelle/jquery-chat#5] opened 2015-04-14 14:49 UTC
some little unalignments in the status select and the search input inside the contact list with chrome version 41.0.2272.118 (64-bit) on Mac OS X, see attachment.

![schermata 2015-04-14 alle 16 47 20](https://cloud.githubusercontent.com/assets/11945313/7139345/0843ef58-e2c6-11e4-9259-6cf4323f6303.png)

**Comment by lovelle** [comment] 2015-04-17 14:20
I did a re work with the search input, please check the latest changes, and please let me know if is now ok to you.
these changes are also merged into demo page, so you not need to download latest commit.

Thanks.

**Comment by marcofaion** [comment] 2015-04-17 15:26
The search field is now ok, but the status select look a bit weird, see attachment

Thanks

![schermata 2015-04-17 alle 17 25 24](https://cloud.githubusercontent.com/assets/11945313/7205069/e1352d4c-e526-11e4-9568-b676236fe964.png)

**Comment by lovelle** [comment] 2015-04-17 17:15
This behavior is expected, when I did it I liked the abiliy to see the difference between the icon status and the selectable icon menu.
I will re think if this is the best option.

thank you very much for your time.

**Comment by lovelle** [comment] 2015-06-20 20:50
closing because is expected behavior. Will remain in that way until anyone claim for change.

**Closed as completed by lovelle** 2015-06-20 20:50 UTC
Labels: graphic issue, Needs design effort
